### ISSUE TITLE
Res and console issue

### ISSUE THREAD

**Issue by tenkoshimu** [badcodestv/fivem-fake-browser#2]
When opening the browser it spams console, also the res is not right do you know how to fix this ?
![afbeelding_2022-12-15_073503639](https://user-images.githubusercontent.com/101616320/207789647-a25a9628-57de-47ec-86fd-4b0903812bd1.png)

**Comment by rpRIGGS** [comment]
Having same problem

**Comment by badcodestv** [comment]
@rpRIGGS @tenkoshimu 

Line 72
Remove the print - `print('tablet', tablet)`

https://github.com/badcodestv/fivem-fake-browser/blob/09437e8c1c1767ad55731939ff79f1e8ce0dac1f/client.lua#L72

**Comment by badcodestv** [comment]
I've updated the repo to remove the print. Sorry about that.

**Comment by badcodestv** [comment]
@tenkoshimu @rpRIGGS 

As far as the resolution goes, view here for changes:

https://github.com/badcodestv/fivem-fake-browser/blob/09437e8c1c1767ad55731939ff79f1e8ce0dac1f/html/css/browser.css#L7

This is the block of CSS that modifies the browser. Modify the width to your likings:

Example: 
`.browser-wrapper {
	...
	width: 50vw; // modify this
	...
}`

This will expand (width wise) the browser. If you need to make height adjustments:

https://github.com/badcodestv/fivem-fake-browser/blob/09437e8c1c1767ad55731939ff79f1e8ce0dac1f/html/css/browser.css#L172

Example:
`.browser-wrapper .browser-content {
	height: 50vh; // make adjustment here
	...
}
`
